<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mapa da sala</title>
</head>
<body>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa.png" usemap="#image-map">


<map name="image-map">
    <area target="" alt="" title="" href="/mapa/bloco/1" coords="486,186,868,254" shape="rect">
    <area target="" alt="" title="" href="/mapa/bloco/1" coords="350,249,476,307" shape="rect">
    <area target="" alt="" title="" href="/mapa/bloco/1" coords="983,185,1222,254" shape="rect">
</map>

</body>
</html>
@stop