@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco2.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 57" title="Sala 57" href="/mapa/sala/57" coords="14,43,145,146" shape="rect">
    <area target="" alt="Sala 58" title="Sala 58" href="/mapa/sala/58" coords="15,146,145,248" shape="0">
    <area target="" alt="Sala 59" title="Sala 59" href="/mapa/sala/59" coords="15,250,145,354" shape="0">
</map>

</body>
</html>
@stop