@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco1.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 06" title="Sala 06" href="/mapa/sala/6" coords="662,155,781,249" shape="rect">
    <area target="" alt="Sala 07" title="Sala 07" href="/mapa/sala/7" coords="531,45,661,140" shape="rect">
    <area target="" alt="Sala 08" title="Sala 08" href="/mapa/sala/8" coords="398,44,529,139" shape="rect">
</map>

</body>
</html>
@stop
