@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco3.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 11" title="Sala 11" href="/mapa/sala/11" coords="836,106,720,7" shape="rect">
    <area target="" alt="Sala 12" title="Sala 12" href="/mapa/sala/12" coords="594,11,720,107" shape="rect">
    <area target="" alt="Sala 13" title="Sala 13" href="/mapa/sala/13" coords="459,9,591,106" shape="rect">
    <area target="" alt="Sala 14" title="Sala 14" href="/mapa/sala/14" coords="324,106,448,178" shape="rect">
    <area target="" alt="Sala 15" title="Sala 15" href="/mapa/sala/15" coords="326,184,447,308" shape="rect">
    <area target="" alt="Sala 18" title="Sala 18" href="/mapa/sala/18" coords="41,308,190,371" shape="rect">
    <area target="" alt="Sala 19" title="Sala 19" href="/mapa/sala/19" coords="44,376,191,437" shape="rect">
    <area target="" alt="Sala 20" title="Sala 20" href="/mapa/sala/20" coords="45,442,220,569" shape="rect">
    <area target="" alt="Sala 22" title="Sala 22" href="/mapa/sala/22" coords="326,557,449,641" shape="rect">
</map>

</body>
</html>
@stop
