@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco9.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 61" title="Sala 61" href="/mapa/sala/61" coords="300,218,416,362" shape="rect">
</map>

</body>
</html>
@stop