@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco5.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 68" title="Sala 68" href="/mapa/sala/68" coords="989,141,1104,237" shape="rect">
    <area target="" alt="Sala 69" title="Sala 69" href="/mapa/sala/69" coords="989,239,1105,337" shape="rect">
    <area target="" alt="Sala 70" title="Sala 70" href="/mapa/sala/70" coords="989,338,1105,437" shape="rect">
    <!--<area target="" alt="Laboratório Enfermagem" title="Laboratório Enfermagem" href="/mapa/sala/1001" coords="28,85,160,249" shape="rect">-->
</map>

</body>
</html>
@stop
