
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mapa da sala</title>
</head>
<body>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/sala_modelo1.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="box-model1" title="box-model1" href="/projeto/edit/{{$projeto_id}}/box/1" coords="159,183,312,234" shape="rect">
    <area target="" style="display:inline-block; background:grey" alt="box-model2" title="box-model2" href="/projeto/edit/{{$projeto_id}}/box/2" coords="3,182,158,235" shape="rect">
    <area target="" alt="box-model3" title="box-model3" href="/projeto/edit/{{$projeto_id}}/box/3" coords="3,1,156,79" shape="rect">
    <area target="" alt="box-model4" title="box-model4" href="/projeto/edit/{{$projeto_id}}/box/4" coords="158,2,313,80" shape="rect">
    <area target="" alt="box-model5" title="box-model5" href="/projeto/edit/{{$projeto_id}}/box/5" coords="315,3,467,80" shape="rect">
</map>


</body>
</html>
