@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco6.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 60" title="Sala 60" href="/mapa/sala/60" coords="295,111,411,218" shape="rect">
    <area target="" alt="Sala 62" title="Sala 62" href="/mapa/sala/62" coords="294,363,410,515" shape="0">
    <area target="" alt="Sala 63" title="Sala 63" href="/mapa/sala/63" coords="646,419,760,515" shape="0">
</map>

</body>
</html>
@stop