@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco3.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Sala 9" title="Sala 9" href="/mapa/sala/9" coords="842,42,960,143" shape="rect">
    <area target="" alt="Sala 10" title="Sala 10" href="/mapa/sala/10" coords="726,42,841,140" shape="rect">
    <area target="" alt="Sala 12" title="Sala 12" href="/mapa/sala/11" coords="359,42,491,144" shape="rect">
    <area target="" alt="Sala 11" title="Sala 11" href="/mapa/sala/12" coords="491,41,608,143" shape="rect">
    <area target="" alt="Sala 13" title="Sala 13" href="/mapa/sala/13" coords="226,42,360,143" shape="rect">
    <area target="" alt="Sala 14" title="Sala 14" href="/mapa/sala/14" coords="86,141,214,217" shape="rect">
</map>

</body>
</html>
@stop