@extends('layouts.app')
@section('content')
<h1 class="text-center alert alert-info">Escolha da sala</h1>

<br>

<h2>Para o seu curso/área estão disponíveis as salas abaixo.</h2>
<blockquote class="blockquote">
    <p class="mb-2 mt-2">Clique em uma sala e depois escolha o box desejado. Os box marcados com um "X"
    estão indisponíveis pois já foram escolhidos por outros alunos.</p>
</blockquote>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/mapa_bloco7.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Saguão" title="Saguão"   href="/mapa/sala/1002" coords="839,65,1083,554" shape="rect">
    <area target="" alt="Sala 21" title="Sala 21" href="/mapa/sala/21" coords="215,219,301,402" shape="rect">
</map>

</body>
</html>
@stop
